### ISSUE TITLE
Support for cmark-gfm

### ISSUE THREAD

**Issue by yoshimaru46** [gonzalezreal/MarkdownUI#61] opened 2021-08-15 11:12 UTC
Is there any plan to support github flavored markdown spec?
refs: https://github.com/github/cmark-gfm

**Comment by gonzalezreal** [comment] 2021-08-19 07:54
Duplicate of #29

**Comment by gonzalezreal** [comment] 2021-08-19 07:56
Hi @yoshimaru46,
This has already been discussed [here](https://github.com/gonzalezreal/MarkdownUI/issues/29#issuecomment-760010908).

**Closed** 2021-08-19 07:57 UTC
